In [6]:
import pandas as pd

data = {
    "ticket_text": [
        "I can't login to my account",
        "Unable to login with correct password",
        "Login failed again and again",
        "Forgot password and unable to login",
        "OTP not received during login",
        "Invalid username or password error",
        "Account locked after multiple login attempts",
        "Login page not loading properly",
        "Unable to sign in to my account",
        "Authentication failed while logging in",
        "My account has been hacked",
        "Someone accessed my account without permission",
        "Unauthorized login detected in my account",
        "My account is compromised",
        "Suspicious activity found on my account",
        "Unknown device logged into my account",
        "I did not make this login attempt",
        "Account security breach detected",
        "My account was accessed from another location",
        "I think my account has been stolen",
        "App is very slow and not responding",
        "App showing error again and again",
        "App is crashing with error message",
        "App not working properly and very slow",
        "Website loading very slow and showing error",
        "App gives error when I try to open it",
        "Facing error in app while using features",
        "App performance is very slow",
        "Getting error on screen while using app",
        "App not opening and showing error",
        "Order not delivered yet",
        "Delivery is late",
        "Order delivery is delayed and not arrived yet",
        "Delivery status shows pending for my order",
        "My order delivery is very late",
        "Order not delivered on expected delivery date",
        "Delivery of my order is still not completed",
        "General query about product",
        "How to reset my password?",
        "How can I update my account information",
        "What is the status of my account",
        "I need help regarding my account details",
        "How to change my account settings",
        "Can you provide information about my account",
        "How can I check my account details",
        "What information is available for my account",
        "I want help with my account information",
        "Payment failed but money deducted",
        "Payment issue while checkout",
        "Need help with billing issue",
        "Refund not received",
        "Refund not initiated yet",
        "Transaction failed but money deducted",
        "Payment failed but money deducted from my account",
        "Refund not received for my payment",
        "Money deducted but payment not completed",
        "Charged twice for the same payment",
        "Payment error and amount debited",
        "Refund amount not credited yet",
        "Payment not working and money deducted",
        "Transaction failed but money debited",
        "Incorrect amount charged during payment",
        "Refund is still pending for my payment",
    ],

    "category": [
        "Login Issue",
        "Login Issue",
        "Login Issue",
        "Login Issue",
        "Login Issue",
        "Login Issue",
        "Login Issue",
        "Login Issue",
        "Login Issue",
        "Login Issue",
        "Security",
        "Security",
        "Security",
        "Security",
        "Security",
        "Security",
        "Security",
        "Security",
        "Security",
        "Security",
        "Technical",
        "Technical",
        "Technical",
        "Technical",
        "Technical",
        "Technical",
        "Technical",
        "Technical",
        "Technical",
        "Technical",
        "Delivery",
        "Delivery",
        "Delivery",
        "Delivery",
        "Delivery",
        "Delivery",
        "Delivery",
        "Query",
        "Query",
        "Query",
        "Query",
        "Query",
        "Query",
        "Query",
        "Query",
        "Query",
        "Query"
        "Billing",
        "Billing",
        "Billing",
        "Billing",
        "Billing",
        "Billing",
        "Billing",
        "Billing",
        "Billing",
        "Billing",
        "Billing",
        "Billing",
        "Billing",
        "Billing",
        "Billing",
        "Billing",
        "Billing",
    ]
}

df = pd.DataFrame(data)
df

                                ticket_text     category
0               I can't login to my account  Login Issue
1     Unable to login with correct password  Login Issue
2              Login failed again and again  Login Issue
3       Forgot password and unable to login  Login Issue
4             OTP not received during login  Login Issue
..                                      ...          ...
58           Refund amount not credited yet      Billing
59   Payment not working and money deducted      Billing
60     Transaction failed but money debited      Billing
61  Incorrect amount charged during payment      Billing
62   Refund is still pending for my payment      Billing

[63 rows x 2 columns]

In [7]:
import re

def clean_text(text):
    text = text.lower()  # sab lowercase
    text = re.sub(r'[^a-zA-Z ]', '', text)  # special characters remove
    return text

df["clean_text"] = df["ticket_text"].apply(clean_text)

df

,ticket_text,category,clean_text
0,I can't login to my account,Login Issue,i cant login to my account
1,Unable to login with correct password,Login Issue,unable to login with correct password
2,Login failed again and again,Login Issue,login failed again and again
3,Forgot password and unable to login,Login Issue,forgot password and unable to login
4,OTP not received during login,Login Issue,otp not received during login
...,...,...,...
58,Refund amount not credited yet,Billing,refund amount not credited yet
59,Payment not working and money deducted,Billing,payment not working and money deducted
60,Transaction failed but money debited,Billing,transaction failed but money debited
61,Incorrect amount charged during payment,Billing,incorrect amount charged during payment
62,Refund is still pending for my payment,Billing,refund is still pending for my payment

In [8]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer()

X = vectorizer.fit_transform(df["clean_text"])

In [9]:
X.shape

(63, 140)

In [10]:
vectorizer.get_feature_names_out()

array(['about', 'accessed', 'account', 'activity', 'after', 'again',
       'amount', 'and', 'another', 'app', 'arrived', 'attempt',
       'attempts', 'authentication', 'available', 'been', 'billing',
       'breach', 'but', 'can', 'cant', 'change', 'charged', 'check',
       'checkout', 'completed', 'compromised', 'correct', 'crashing',
       'credited', 'date', 'debited', 'deducted', 'delayed', 'delivered',
       'delivery', 'details', 'detected', 'device', 'did', 'during',
       'error', 'expected', 'facing', 'failed', 'features', 'for',
       'forgot', 'found', 'from', 'general', 'getting', 'gives', 'hacked',
       'has', 'help', 'how', 'in', 'incorrect', 'information',
       'initiated', 'into', 'invalid', 'is', 'issue', 'it', 'late',
       'loading', 'location', 'locked', 'logged', 'logging', 'login',
       'make', 'message', 'money', 'multiple', 'my', 'need', 'not', 'of',
       'on', 'open', 'opening', 'or', 'order', 'otp', 'page', 'password',
       'payment', 'pending', 'performance', 'permission', 'product',
       'properly', 'provide', 'query', 'received', 'refund', 'regarding',
       'reset', 'responding', 'same', 'screen', 'security', 'settings',
       'showing', 'shows', 'sign', 'slow', 'someone', 'status', 'still',
       'stolen', 'suspicious', 'the', 'think', 'this', 'to',
       'transaction', 'try', 'twice', 'unable', 'unauthorized', 'unknown',
       'update', 'username', 'using', 'very', 'want', 'was', 'website',
       'what', 'when', 'while', 'with', 'without', 'working', 'yet',
       'you'], dtype=object)

In [11]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression()

model.fit(X, df["category"])

LogisticRegression()

In [12]:
model

LogisticRegression()

In [13]:
test = ["payment not working"]

# clean karo
test_clean = [clean_text(t) for t in test]

# numbers me convert
test_vec = vectorizer.transform(test_clean)

# prediction
model.predict(test_vec)

array(['Billing'], dtype=object)

In [15]:
def get_priority(text):
    text = text.lower()

    if "urgent" in text or "hacked" in text or "breach" in text:
        return "High"
    elif "failed" in text or "not working" in text or "error" in text:
        return "Medium"
    else:
        return "Low"

In [16]:
def predict_ticket(text):
    clean = clean_text(text)
    vec = vectorizer.transform([clean])

    category = model.predict(vec)[0]
    priority = get_priority(text)

    return category, priority

In [17]:
predict_ticket("My account hacked please help urgently")

('Security', 'High')

In [18]:
import pickle

pickle.dump(model, open("model.pkl", "wb"))
pickle.dump(vectorizer, open("tfidf.pkl", "wb"))

In [19]:
from google.colab import files

files.download("model.pkl")
files.download("tfidf.pkl")